name: basic_cleaning
channels:
  - conda-forge
  - defaults
dependencies:
  - hydra-core=1.3.2
  - matplotlib=3.8.2
  - pandas=1.1.4
  - pip=20.3.3
  - mlflow=1.30.0
  - scikit-learn=1.5.0
  - pip:
      - databricks_cli==0.18.0
      - wandb==0.10.21
